
CREATE DATABASE IF NOT EXISTS QL_KHACHSAN CHARACTER SET 'UTF8' COLLATE 'UTF8_UNICODE_CI';

USE QL_KHACHSAN;


CREATE TABLE IF NOT EXISTS NHANVIEN
(
 MANV VARCHAR(11) NOT NULL,
 TENNV VARCHAR(50) NOT NULL,
 CHUCVU VARCHAR(50),
 LUONGNV DOUBLE,
 NGAYSINH DATE,
 GIOITINH CHAR(3),
 CHUTHICH VARCHAR(50),
 
 CONSTRAINT pk_NHANVIEN PRIMARY KEY NHANVIEN(MANV)
 
 );
 
 CREATE TABLE IF NOT EXISTS DICHVU
(
 MADV VARCHAR(11) NOT NULL,
 TENDV VARCHAR(50) NOT NULL,
 GIADV DOUBLE,
 
 CONSTRAINT pk_DICHVU PRIMARY KEY DICHVU(MADV)
 
 );
 
 CREATE TABLE IF NOT EXISTS PHONG
(
 MAPHONG VARCHAR(11) NOT NULL,
 TENPHONG VARCHAR(50) NOT NULL,
 LOAIPHONG VARCHAR(20) NOT NULL,
 GIAPHONG DOUBLE,
 CHUTHICH VARCHAR(50),
 TINHTRANG VARCHAR(50),
 MANV VARCHAR(11),
 MADV VARCHAR(11),
 
 CONSTRAINT pk_PHONG PRIMARY KEY PHONG(MAPHONG),
 CONSTRAINT fk_NHANVIEN1 FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV),
 CONSTRAINT fk_DICHVU FOREIGN KEY (MADV) REFERENCES DICHVU(MADV)
 
);


CREATE TABLE IF NOT EXISTS KHACHHANG
(
 MAKH VARCHAR(11) NOT NULL,
 TENKH VARCHAR(50) NOT NULL,
 CMND VARCHAR(20) NOT NULL,
 QUOCTICH VARCHAR(50),
 GIOITINH CHAR(3),
 TUOI INT(3),
 SDT VARCHAR(20),
 MAPHONG VARCHAR(11),
 
 CONSTRAINT pk_KHACHHANG PRIMARY KEY KHACHHANG(MAKH),
 CONSTRAINT fk_PHONG FOREIGN KEY (MAPHONG) REFERENCES PHONG(MAPHONG)
 
 );
 
 CREATE TABLE IF NOT EXISTS HOADON
(
 MAHD VARCHAR(11) NOT NULL,
 MANV VARCHAR(11),
 MAPHONG VARCHAR(11),
 NGAY DATE,
 GIAHD DOUBLE,
 CONSTRAINT pk_HOADON PRIMARY KEY HOADON(MAHD),
 CONSTRAINT fk_NHANVIEN2 FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV),
 CONSTRAINT fk_PHONG2 FOREIGN KEY (MAPHONG) REFERENCES PHONG(MAPHONG)
 
 
 );
 















